### ISSUE TITLE
关于LooperViewPager BUG

### ISSUE THREAD

**Issue by ouacyou** [TracyZhangLei/LoopViewPager#1]
请问你修复的是哪两个bug，我发现如果一张图片加载失败的话，再切换的话会闪一下，不知道你修复的是不是这个bug。

**Comment by TracyZhangLei** [comment]
修复了第一次向左滑闪烁bug，禁止了一个item时滑动这两个

**Comment by TracyZhangLei** [comment]
修复了第一次向左滑闪烁bug，禁止了一个item时滑动这两个

**Comment by 274921407** [comment]
非常感谢 你解决了这个BUG 。。。。。另外，当数据发生变化时 ，用noti 还是重新setadapter?

**Comment by TracyZhangLei** [comment]
@274921407 notify是不管用的，看一下代码就知道了，如果数据变化需要重新调用setAdapter
